# ===================================================================
#                   Swagger configuration
# ===================================================================

swagger:
  title: 'TimeLog Users'
  description: 'TimeLog Users Service'
  contact:
    name: 'Sune Thomas Poulsen'
    url: ''
    email: 'sunepoulsen@gmail.com'
  license: 'Apache License Version 2.0'
  licenseUrl: 'https://github.com/springfox/springfox/blob/master/LICENSE'
  version: '2.0'

logging:
  level:
    dk.sunepoulsen.timelog: INFO
